html: "img/icons/html.png"
css: "img/icons/css.png"
bootstrap: "img/icons/bootstrap.png"
php: "img/icons/php.png"
symfony: "img/icons/symfony.png"
git: "img/icons/git.png"
js: "img/icons/js.png"
sql: "img/icons/sql.png"
composer: "img/icons/composer.png"
wordpress: "img/icons/wordpress.png"
uml: "img/icons/uml.png"
